import mongoose from "mongoose";
import bcrypt from "bcrypt";
import User from "../models/User.js";

const buildUsers = (hashedPassword) => [
  {
    fullName: "Amit Sharma",
    email: "user1@altcredit.com",
    phone: "9870000001",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "M",
    flagOwnCar: true,
    flagOwnRealty: true,
    cntChildren: 2,
    incomTotal: 320000,
    amtCredit: 550000,
    goodsPrice: 500000,
    nameIncomeType: "Working",
    nameEducationType: "Higher education",
    nameContractType: "Cash loans",
    daysEmployed: -1850,
    ownCarAge: 6,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 4,
    daysBirth: -13000,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Priya Mehta",
    email: "user2@altcredit.com",
    phone: "9870000002",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "F",
    flagOwnCar: false,
    flagOwnRealty: true,
    cntChildren: 1,
    incomTotal: 280000,
    amtCredit: 420000,
    goodsPrice: 380000,
    nameIncomeType: "Commercial associate",
    nameEducationType: "Academic degree",
    nameContractType: "Revolving loans",
    daysEmployed: -1420,
    ownCarAge: null,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 3,
    daysBirth: -12150,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Ravi Kumar",
    email: "user3@altcredit.com",
    phone: "9870000003",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "M",
    flagOwnCar: true,
    flagOwnRealty: false,
    cntChildren: 0,
    incomTotal: 210000,
    amtCredit: 300000,
    goodsPrice: 250000,
    nameIncomeType: "State servant",
    nameEducationType: "Secondary / secondary special",
    nameContractType: "Cash loans",
    daysEmployed: -980,
    ownCarAge: 4,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 2,
    daysBirth: -11880,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Sneha Iyer",
    email: "user4@altcredit.com",
    phone: "9870000004",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "F",
    flagOwnCar: false,
    flagOwnRealty: false,
    cntChildren: 0,
    incomTotal: 90000,
    amtCredit: 120000,
    goodsPrice: 90000,
    nameIncomeType: "Student",
    nameEducationType: "Incomplete higher",
    nameContractType: "Revolving loans",
    daysEmployed: -320,
    ownCarAge: null,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 1,
    daysBirth: -10120,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Karan Malhotra",
    email: "user5@altcredit.com",
    phone: "9870000005",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "M",
    flagOwnCar: true,
    flagOwnRealty: true,
    cntChildren: 3,
    incomTotal: 450000,
    amtCredit: 900000,
    goodsPrice: 800000,
    nameIncomeType: "Working",
    nameEducationType: "Higher education",
    nameContractType: "Cash loans",
    daysEmployed: -3500,
    ownCarAge: 12,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 5,
    daysBirth: -17000,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Neha Joshi",
    email: "user6@altcredit.com",
    phone: "9870000006",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "F",
    flagOwnCar: true,
    flagOwnRealty: false,
    cntChildren: 1,
    incomTotal: 180000,
    amtCredit: 250000,
    goodsPrice: 200000,
    nameIncomeType: "Commercial associate",
    nameEducationType: "Lower secondary",
    nameContractType: "Revolving loans",
    daysEmployed: -760,
    ownCarAge: 2,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 3,
    daysBirth: -14500,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Arvind Rao",
    email: "user7@altcredit.com",
    phone: "9870000007",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "M",
    flagOwnCar: false,
    flagOwnRealty: true,
    cntChildren: 2,
    incomTotal: 240000,
    amtCredit: 360000,
    goodsPrice: 300000,
    nameIncomeType: "State servant",
    nameEducationType: "Secondary / secondary special",
    nameContractType: "Cash loans",
    daysEmployed: -2200,
    ownCarAge: null,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 4,
    daysBirth: -16080,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Sunita Verma",
    email: "user8@altcredit.com",
    phone: "9870000008",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "F",
    flagOwnCar: false,
    flagOwnRealty: true,
    cntChildren: 1,
    incomTotal: 150000,
    amtCredit: 200000,
    goodsPrice: 170000,
    nameIncomeType: "Pensioner",
    nameEducationType: "Lower secondary",
    nameContractType: "Cash loans",
    daysEmployed: -3600,
    ownCarAge: null,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 2,
    daysBirth: -21900,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Vikram Singh",
    email: "user9@altcredit.com",
    phone: "9870000009",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "M",
    flagOwnCar: true,
    flagOwnRealty: false,
    cntChildren: 0,
    incomTotal: 390000,
    amtCredit: 740000,
    goodsPrice: 690000,
    nameIncomeType: "Working",
    nameEducationType: "Academic degree",
    nameContractType: "Revolving loans",
    daysEmployed: -2900,
    ownCarAge: 9,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 2,
    daysBirth: -15020,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Pooja Nair",
    email: "user10@altcredit.com",
    phone: "9870000010",
    password: hashedPassword,
    isOnBoarded: true,
    role: "user",
    gender: "F",
    flagOwnCar: true,
    flagOwnRealty: true,
    cntChildren: 2,
    incomTotal: 260000,
    amtCredit: 480000,
    goodsPrice: 430000,
    nameIncomeType: "Commercial associate",
    nameEducationType: "Incomplete higher",
    nameContractType: "Cash loans",
    daysEmployed: -1320,
    ownCarAge: 5,
    flagMobile: true,
    flagEmail: true,
    cntFamMembers: 4,
    daysBirth: -13540,
    creditScore: null,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Personal Loan Admin",
    email: "admin.personal@altcredit.com",
    phone: "9890000001",
    password: hashedPassword,
    isOnBoarded: true,
    role: "admin",
    adminLoanType: "personal",
    flagMobile: true,
    flagEmail: true,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Home Loan Admin",
    email: "admin.home@altcredit.com",
    phone: "9890000002",
    password: hashedPassword,
    isOnBoarded: true,
    role: "admin",
    adminLoanType: "home",
    flagMobile: true,
    flagEmail: true,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Education Loan Admin",
    email: "admin.education@altcredit.com",
    phone: "9890000003",
    password: hashedPassword,
    isOnBoarded: true,
    role: "admin",
    adminLoanType: "education",
    flagMobile: true,
    flagEmail: true,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Auto Loan Admin",
    email: "admin.auto@altcredit.com",
    phone: "9890000004",
    password: hashedPassword,
    isOnBoarded: true,
    role: "admin",
    adminLoanType: "auto",
    flagMobile: true,
    flagEmail: true,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Business Loan Admin",
    email: "admin.business@altcredit.com",
    phone: "9890000005",
    password: hashedPassword,
    isOnBoarded: true,
    role: "admin",
    adminLoanType: "business",
    flagMobile: true,
    flagEmail: true,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
  {
    fullName: "Credit Card Admin",
    email: "admin.creditcard@altcredit.com",
    phone: "9890000006",
    password: hashedPassword,
    isOnBoarded: true,
    role: "admin",
    adminLoanType: "credit_card",
    flagMobile: true,
    flagEmail: true,
    creditStage: 1,
    loginAttempts: 0,
    isActive: true,
  },
];

const seedUsers = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    const hashedPassword = await bcrypt.hash("Password@123", 10);
    const users = buildUsers(hashedPassword);

    await User.deleteMany({
      $or: [
        { email: { $in: users.map((user) => user.email) } },
        { phone: { $in: users.map((user) => user.phone) } },
      ],
    });

    const insertedUsers = await User.insertMany(users);
    console.log(`Seeded ${insertedUsers.length} users`);
  } catch (error) {
    console.error("Seeding failed:", error.message);
  } finally {
    await mongoose.disconnect();
  }
};

seedUsers();
